databases:
  - name: beautiful_docs
    databaseName: beautiful_docs_production
    user: beautiful_docs
    plan: starter

services:
  - type: web
    name:  beautiful_docs
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4 # sensible default
      - key: SERVER_URL
        value: https://beautiful-docs-app.onrender.com
      - key: HOST
        value: beautiful-docs-app