---
openapi: 3.0.1
info:
  description: The Beautiful Docs API V1 is a REST interface designed to transform
    the [Beautiful Docs repository](https://github.com/matheusfelipeog/beautiful-docs)
    into a structured and accessible API. This API provides access to the documentation
    resources curated by [matheusfelipeog](https://github.com/matheusfelipeog) and
    other developers. Built to enhance the usability of the original repository, this
    API simplifies the process of integrating and exploring high-quality documentation
    by offering endpoints tailored for easy access and interaction.
  termsOfService: http://localhost:3000/terms
  contact:
    email: rachel@moonrocks.dev
  title: Beautiful Docs API V1
  version: v1
paths:
  "/documents":
    get:
      summary: Lists all documents
      tags:
      - Documents
      responses:
        '200':
          description: succesful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/documents"
        '404':
          description: documents not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors"
  "/documents/{id}":
    get:
      summary: Retrieves a document
      tags:
      - Documents
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: succesful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/documents"
        '404':
          description: document not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors"
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost
tags:
- name: Documents
  description: All the beautiful docs in one place
  externalDocs:
    description: Original source
    url: https://github.com/matheusfelipeog/beautiful-docs
components:
  schemas:
    documents:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              type:
                type: string
              attributes:
                type: object
                properties:
                  title:
                    type: string
                  url:
                    type: string
                  description:
                    type: string
                  contributor:
                    type: string
                required:
                - url
    errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              source:
                type: object
                properties:
                  pointer:
                    type: string
              detail:
                type: string
              status:
                type: integer
